import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, CalendarDays, Car, Check, ChevronLeft, ChevronRight, CircleCheck, Clock3, Droplets, Facebook, Instagram, Mail, MapPin, Menu, MessageCircle, Phone, ShieldCheck, Sparkles, Star, X, Youtube } from 'lucide-react';

const business = { name: 'Perfect Car Studio', phone: '+91 97990 75458', whatsapp: '919799075458', email: 'hello@perfectcarstudio.in', address: 'Perfect Car Studio, near RIICO Industrial Area, RIICO Industrial Area, Sheoganj, Rajasthan 307027', hours: 'Mon–Sat · 9:00 AM–8:00 PM' };
const images = {
  hero: 'https://images.pexels.com/photos/8012523/pexels-photo-8012523.jpeg?auto=compress&cs=tinysrgb&h=1600&w=2400',
  wash: 'https://images.pexels.com/photos/6873078/pexels-photo-6873078.jpeg?auto=compress&cs=tinysrgb&h=900&w=1400',
  interior: 'https://images.pexels.com/photos/5233285/pexels-photo-5233285.jpeg?auto=compress&cs=tinysrgb&h=900&w=1400',
  deep: 'https://images.pexels.com/photos/6873103/pexels-photo-6873103.jpeg?auto=compress&cs=tinysrgb&h=900&w=1400',
  detail: 'https://images.pexels.com/photos/6870296/pexels-photo-6870296.jpeg?auto=compress&cs=tinysrgb&h=900&w=1400',
};
const services = [
  { title: 'Car Wash', eyebrow: '01 / Exterior', description: 'A meticulous exterior reset that lifts away road film and restores a clean, confident finish.', image: images.wash, icon: Droplets, tags: ['Foam wash', 'Wheel clean', 'Dry finish'] },
  { title: 'Interior Cleaning', eyebrow: '02 / Cabin care', description: 'A considered clean for the spaces you spend time in — seats, surfaces, mats and every detail.', image: images.interior, icon: Sparkles, tags: ['Vacuum', 'Dashboard', 'Seat care'] },
  { title: 'Deep Interior Cleaning', eyebrow: '03 / Full refresh', description: 'A deeper treatment for tired interiors, stubborn marks and a cabin that needs a complete refresh.', image: images.deep, icon: ShieldCheck, tags: ['Deep vacuum', 'Carpet care', 'Stain lift'] },
  { title: 'Car Detailing', eyebrow: '04 / Studio finish', description: 'Precision-led detailing for those who expect more from the final finish of their vehicle.', image: images.detail, icon: Car, tags: ['Polish', 'Hard-to-reach', 'Final finish'] },
];
const gallery = [
  { image: images.wash, category: 'Washing', title: 'Foam & finesse' },
  { image: images.interior, category: 'Interior', title: 'Cabin reset' },
  { image: 'https://images.pexels.com/photos/9784202/pexels-photo-9784202.jpeg?auto=compress&cs=tinysrgb&h=1000&w=1400', category: 'Exterior', title: 'After the rain' },
  { image: images.detail, category: 'Detailing', title: 'The final pass' },
  { image: 'https://images.pexels.com/photos/14231678/pexels-photo-14231678.jpeg?auto=compress&cs=tinysrgb&h=1000&w=1400', category: 'Washing', title: 'Clean by design' },
];
const testimonials = [
  { quote: 'The kind of care you notice the moment you get back in the car. Everything felt considered, fresh and genuinely premium.', name: 'Jitenra', detail: 'Interior cleaning' },
  { quote: 'Easy to book, clear communication and a finish that looks beautiful in the sunlight. I will definitely be back.', name: 'Rakesh', detail: 'Car detailing' },
];

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [bookingOpen, setBookingOpen] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [galleryFilter, setGalleryFilter] = useState('All');
  const [lightbox, setLightbox] = useState<number | null>(null);
  const [beforeAfter, setBeforeAfter] = useState(54);
  const [testimonial, setTestimonial] = useState(0);
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 32); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll); }, []);
  const filteredGallery = galleryFilter === 'All' ? gallery : gallery.filter((item) => item.category === galleryFilter);
  const whatsappLink = `https://wa.me/${business.whatsapp}?text=${encodeURIComponent('Hello Perfect Car Studio, I would like to know more about your car care services.')}`;
  const closeBooking = () => { setBookingOpen(false); setSubmitted(false); };
  const handleBookingSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const controls = Array.from(event.currentTarget.elements).filter((element): element is HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement => 'value' in element) as (HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement)[];
    const booking = {
      customer_name: controls[0]?.value || '',
      mobile: controls[1]?.value || '',
      service_id: controls[2]?.value || '',
      booking_date: controls[3]?.value || '',
      start_time: controls[4]?.value || '',
      vehicle_type: '',
      notes: controls[5]?.value || '',
    };
    try {
      const response = await fetch(import.meta.env.VITE_BOOKING_API_URL, { method: 'POST', headers: { 'Content-Type': 'text/plain;charset=utf-8' }, body: JSON.stringify(booking) });
      const result = await response.json() as { success?: boolean; error?: string; booking_id?: string };
      if (!response.ok || result.success === false) throw new Error(result.error || 'Unable to submit booking');
      const message = [`New booking request - ${business.name}`, '', `Booking ID: ${result.booking_id || 'Pending'}`, `Name: ${booking.customer_name}`, `Mobile: ${booking.mobile}`, `Service: ${booking.service_id}`, `Date: ${booking.booking_date}`, `Preferred time: ${booking.start_time}`, `Notes: ${booking.notes || 'None'}`, '', 'Please confirm availability.'].join('\n');
      window.open(`https://wa.me/${business.whatsapp}?text=${encodeURIComponent(message)}`, '_blank', 'noopener,noreferrer');
      setSubmitted(true);
    } catch (error) {
      window.alert(error instanceof Error ? error.message : 'Unable to submit booking. Please try again.');
    }
  };
  const navItems = [['Home', '/'], ['Services', '/services'], ['Our approach', '/about'], ['Gallery', '/gallery'], ['Contact', '/contact']];
  return (
    <div className="site-shell">
      <header className={`navbar ${scrolled ? 'navbar-scrolled' : ''}`}>
        <a href="#top" className="brand" aria-label="Perfect Car Studio home"><img src="/assets/images/PCS_LOGO.jpg" alt="Perfect Car Studio" /><span>PERFECT <b>CAR STUDIO</b></span></a>
        <nav className="desktop-nav" aria-label="Primary navigation">{navItems.map(([label, href]) => <a key={label} href={href}>{label}</a>)}</nav>
        <button className="button button-accent nav-cta" onClick={() => setBookingOpen(true)}>Book a service <ArrowRight size={16} /></button>
        <button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu" aria-expanded={menuOpen}>{menuOpen ? <X /> : <Menu />}</button>
      </header>
      {menuOpen && <div className="mobile-menu"><nav>{navItems.map(([label, href]) => <a key={label} href={href} onClick={() => setMenuOpen(false)}>{label}<ArrowRight size={16} /></a>)}</nav><button className="button button-accent" onClick={() => { setBookingOpen(true); setMenuOpen(false); }}>Book a service <ArrowRight size={16} /></button></div>}
      <main id="top">
        <section className="hero section-dark"><div className="hero-image" style={{ backgroundImage: `url(${images.hero})` }} /><div className="hero-overlay" /><div className="container hero-content"><div className="hero-copy reveal"><div className="eyebrow"><span className="eyebrow-line" /> Premium automotive care</div><h1>Perfection in<br /><em>every detail.</em></h1><p className="hero-lede">Professional washing, interior care and detailing for the vehicle you choose every day.</p><div className="hero-actions"><button className="button button-accent" onClick={() => setBookingOpen(true)}>Book your service <ArrowRight size={17} /></button><a className="text-link" href="#services">Explore services <ArrowDown size={16} /></a></div><div className="hero-meta"><span><span className="status-dot" /> Now accepting bookings</span><span>Mon–Sat / 09:00–20:00</span></div></div><a href="#services" className="scroll-cue"><span>Scroll to explore</span><ArrowDown size={15} /></a></div></section>
        <section className="trust-bar"><div className="container trust-grid">{[{ icon: ShieldCheck, title: 'Carefully handled', text: 'Your car, treated with respect' }, { icon: Sparkles, title: 'Studio quality', text: 'Thoughtful care, clean results' }, { icon: Clock3, title: 'Made convenient', text: 'Simple booking, clear updates' }, { icon: CircleCheck, title: 'Ready when you are', text: 'Easy call and WhatsApp access' }].map(({ icon: Icon, title, text }) => <div className="trust-item" key={title}><Icon size={22} strokeWidth={1.4} /><div><strong>{title}</strong><span>{text}</span></div></div>)}</div></section>
        <section id="services" className="section section-surface"><div className="container"><SectionHeading eyebrow="Our services" title={<>Care that goes<br /><em>beyond clean.</em></>} intro="From a quick exterior reset to a considered interior refresh, every service is built around the details that make a difference." action={<a className="text-link" href="#contact">Need a recommendation? <ArrowRight size={16} /></a>} /><div className="service-grid">{services.map(({ title, eyebrow, description, image, icon: Icon, tags }, index) => <article className="service-card" key={title}><div className="service-card-image"><img src={image} alt={title} loading="lazy" /><span className="service-number">{String(index + 1).padStart(2, '0')}</span><span className="image-arrow"><ArrowUpRight size={18} /></span></div><div className="service-card-body"><div className="service-card-title"><div><p className="card-eyebrow">{eyebrow}</p><h3>{title}</h3></div><Icon size={20} strokeWidth={1.3} /></div><p>{description}</p><div className="tag-row">{tags.map((tag) => <span key={tag}>{tag}</span>)}</div><button className="card-link" onClick={() => setBookingOpen(true)}>Book this service <ArrowRight size={15} /></button></div></article>)}</div></div></section>
        <section className="section before-after-section"><div className="container split-section"><div className="before-copy"><p className="eyebrow"><span className="eyebrow-line" /> The difference is visible</p><h2>Leave with a car<br />that feels <em>new.</em></h2><p>Professional care is more than a quick rinse. It is the calm of a clean cabin, the confidence of a clear finish and the pleasure of getting back behind the wheel.</p><ul className="check-list"><li><Check size={16} /> Careful, methodical process</li><li><Check size={16} /> Quality products and equipment</li><li><Check size={16} /> A finish you can feel</li></ul><button className="button button-outline" onClick={() => setBookingOpen(true)}>Start your transformation <ArrowRight size={16} /></button></div><div className="comparison"><div className="comparison-image comparison-before" style={{ backgroundImage: `url(${images.interior})` }} /><div className="comparison-image comparison-after" style={{ backgroundImage: `url(${images.detail})`, width: `${beforeAfter}%` }} /><div className="comparison-labels"><span>Before</span><span>After</span></div><input className="comparison-range" type="range" min="15" max="85" value={beforeAfter} onChange={(e) => setBeforeAfter(Number(e.target.value))} aria-label="Compare before and after" /><div className="comparison-handle" style={{ left: `${beforeAfter}%` }}><ChevronLeft size={14} /><ChevronRight size={14} /></div></div></div></section>
        <section id="approach" className="section approach-section"><div className="container"><SectionHeading eyebrow="Why Perfect Car Studio" title={<>A better standard<br />of <em>car care.</em></>} intro="We keep the experience clear, the work precise and the result worth coming back for." /><div className="approach-grid">{[{ number: '01', title: 'Attention to detail', text: 'We take the time to clean the places that are easy to miss.' }, { number: '02', title: 'Professional methods', text: 'Purposeful tools and considered techniques, used with care.' }, { number: '03', title: 'Complete care', text: 'Exterior, interior and finishing — all in one calm experience.' }, { number: '04', title: 'A studio mindset', text: 'Clean, focused and respectful from arrival to handover.' }].map((item) => <div className="approach-item" key={item.number}><span>{item.number}</span><div><h3>{item.title}</h3><p>{item.text}</p></div><ArrowUpRight size={18} /></div>)}</div></div></section>
        <section className="section process-section"><div className="container"><div className="process-header"><SectionHeading eyebrow="The process" title={<>Car care,<br /><em>made simple.</em></>} intro="No guesswork. Just a straightforward path to a better-looking, better-feeling car." /><button className="button button-accent" onClick={() => setBookingOpen(true)}>Book a visit <CalendarDays size={17} /></button></div><div className="process-grid">{[{ n: '01', title: 'Choose your service', text: 'Tell us what your car needs.' }, { n: '02', title: 'Book your visit', text: 'Pick a time that suits you.' }, { n: '03', title: 'We care for your car', text: 'Our team gets to work.' }, { n: '04', title: 'Drive away fresh', text: 'Enjoy the finished result.' }].map((step) => <div className="process-step" key={step.n}><span className="process-n">{step.n}</span><div className="process-line" /><h3>{step.title}</h3><p>{step.text}</p></div>)}</div></div></section>
        <section id="gallery" className="section section-surface gallery-section"><div className="container"><SectionHeading eyebrow="A glimpse inside" title={<>The work speaks<br /><em>for itself.</em></>} intro="A few moments from the studio. Your car could be next." /><div className="filter-row" role="tablist">{['All', 'Exterior', 'Interior', 'Washing', 'Detailing'].map((filter) => <button key={filter} className={galleryFilter === filter ? 'filter-active' : ''} onClick={() => setGalleryFilter(filter)}>{filter}</button>)}</div><div className="gallery-grid">{filteredGallery.map((item, index) => <button className={`gallery-item gallery-item-${index + 1}`} key={item.title} onClick={() => setLightbox(gallery.findIndex((photo) => photo.title === item.title))}><img src={item.image} alt={item.title} loading="lazy" /><span className="gallery-overlay"><small>{item.category}</small><strong>{item.title}</strong><ArrowUpRight size={18} /></span></button>)}</div></div></section>
        <section className="quote-section"><div className="container quote-inner"><div className="quote-mark">“</div><div className="quote-content"><div className="stars">{[1, 2, 3, 4, 5].map((star) => <Star key={star} size={16} fill="currentColor" />)}</div><blockquote>{testimonials[testimonial].quote}</blockquote><div className="quote-person"><strong>{testimonials[testimonial].name}</strong><span>{testimonials[testimonial].detail}</span></div><div className="quote-controls"><button onClick={() => setTestimonial((testimonial - 1 + testimonials.length) % testimonials.length)} aria-label="Previous testimonial"><ChevronLeft size={17} /></button><span>0{testimonial + 1} <i>/</i> 0{testimonials.length}</span><button onClick={() => setTestimonial((testimonial + 1) % testimonials.length)} aria-label="Next testimonial"><ChevronRight size={17} /></button></div></div></div></section>
        <section className="cta-section"><div className="cta-image" style={{ backgroundImage: `url(${images.detail})` }} /><div className="cta-overlay" /><div className="container cta-content"><p className="eyebrow"><span className="eyebrow-line" /> Your car deserves better care</p><h2>Ready for a<br /><em>fresh start?</em></h2><p>Book a visit or speak with us on WhatsApp. We will help you find the right care for your car.</p><div className="hero-actions"><button className="button button-accent" onClick={() => setBookingOpen(true)}>Book now <ArrowRight size={17} /></button><a href={whatsappLink} target="_blank" rel="noreferrer" className="button button-light"><MessageCircle size={17} /> WhatsApp us</a></div></div></section>
        <section id="contact" className="section contact-section"><div className="container contact-grid"><div><SectionHeading eyebrow="Visit the studio" title={<>Let's take care<br />of your <em>car.</em></>} intro="Have a question or know what your car needs? We are happy to help." /><div className="contact-links"><a href={`tel:${business.phone.replace(/\s/g, '')}`}><span><Phone size={17} /></span><div><small>Call us</small><strong>{business.phone}</strong></div><ArrowUpRight size={17} /></a><a href={whatsappLink} target="_blank" rel="noreferrer"><span><MessageCircle size={17} /></span><div><small>WhatsApp</small><strong>Start a conversation</strong></div><ArrowUpRight size={17} /></a><a href="#map"><span><MapPin size={17} /></span><div><small>Find us</small><strong>{business.address}</strong></div><ArrowUpRight size={17} /></a></div></div><div className="contact-card"><div className="contact-card-top"><p className="card-eyebrow">Send an enquiry</p><h3>Tell us about your car.</h3><p>We will get back to you with a helpful recommendation.</p></div><form onSubmit={(e) => { e.preventDefault(); setSubmitted(true); }}><label>Full name<input required type="text" placeholder="Your name" /></label><label>Mobile number<input required type="tel" placeholder="Your mobile number" /></label><label>What do you need?<select defaultValue=""><option value="" disabled>Select a service</option>{services.map((service) => <option key={service.title}>{service.title}</option>)}</select></label><label>Message<textarea placeholder="Anything we should know?" rows={3} /></label><button className="button button-accent" type="submit">Send enquiry <ArrowRight size={16} /></button>{submitted && <p className="form-success"><CircleCheck size={16} /> Thanks — we will be in touch shortly.</p>}</form></div></div></section>
      </main>
      <footer className="footer"><div className="container footer-grid"><div className="footer-brand"><a href="#top" className="brand"><img src="/assets/images/PCS_LOGO.jpg" alt="Perfect Car Studio" /><span>PERFECT <b>CAR STUDIO</b></span></a><p>Premium washing, interior care and detailing for the vehicle you choose every day.</p><div className="socials"><a href="#contact" aria-label="Instagram"><Instagram size={17} /></a><a href="#contact" aria-label="Facebook"><Facebook size={17} /></a><a href="#contact" aria-label="YouTube"><Youtube size={17} /></a></div></div><div><p className="footer-label">Explore</p><a href="#services">Services</a><a href="#approach">Our approach</a><a href="#gallery">Gallery</a><a href="#contact">Contact</a></div><div><p className="footer-label">Contact</p><a href={`tel:${business.phone.replace(/\s/g, '')}`}>{business.phone}</a><a href={whatsappLink}>WhatsApp us</a><a href="#contact">{business.hours}</a></div><div><p className="footer-label">Stay in the know</p><p className="footer-note">Thoughtful car care, occasional studio news. Nothing noisy.</p><div className="email-row"><Mail size={16} /><input type="email" aria-label="Email address" placeholder="Your email address" /><button aria-label="Subscribe"><ArrowRight size={16} /></button></div></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Perfect Car Studio</span><span>Built around care & detail</span></div></footer>
      <a href={whatsappLink} target="_blank" rel="noreferrer" className="whatsapp-float" aria-label="Chat on WhatsApp"><MessageCircle size={22} /></a><div className="mobile-actions"><a href={`tel:${business.phone.replace(/\s/g, '')}`}><Phone size={16} /> Call</a><a href={whatsappLink} target="_blank" rel="noreferrer"><MessageCircle size={16} /> WhatsApp</a><button onClick={() => setBookingOpen(true)}><CalendarDays size={16} /> Book now</button></div>
      {lightbox !== null && <div className="lightbox" role="dialog" aria-modal="true" onClick={() => setLightbox(null)}><button className="lightbox-close" onClick={() => setLightbox(null)} aria-label="Close gallery"><X /></button><img src={gallery[lightbox].image} alt={gallery[lightbox].title} onClick={(e) => e.stopPropagation()} /><div className="lightbox-caption">{gallery[lightbox].category} <strong>{gallery[lightbox].title}</strong></div></div>}
      {bookingOpen && <div className="modal-backdrop" onClick={closeBooking}><div className="booking-modal" onClick={(e) => e.stopPropagation()}><button className="modal-close" onClick={closeBooking} aria-label="Close booking"><X size={20} /></button>{submitted ? <div className="booking-success"><CircleCheck size={42} /><p className="eyebrow">Request received</p><h2>We will be in<br /><em>touch shortly.</em></h2><p>Your booking request is with the studio. We will contact you to confirm availability and the next steps.</p><button className="button button-accent" onClick={closeBooking}>Back to the studio <ArrowRight size={16} /></button></div> : <><p className="eyebrow"><span className="eyebrow-line" /> Book a service</p><h2>Let's make time<br />for <em>your car.</em></h2><p className="modal-intro">Share a few details and we will help you find the right service.</p><form onSubmit={handleBookingSubmit}><label>Full name<input required type="text" placeholder="Your name" /></label><label>Mobile number<input required type="tel" placeholder="Your mobile number" /></label><label>Service<select required defaultValue=""><option value="" disabled>Choose a service</option>{services.map((service) => <option key={service.title}>{service.title}</option>)}</select></label><div className="form-row"><label>Preferred date<input required type="date" /></label><label>Preferred time<select required defaultValue=""><option value="" disabled>Choose time</option><option>Morning</option><option>Afternoon</option><option>Evening</option></select></label></div><label>Anything we should know?<textarea rows={3} placeholder="Optional notes about your car" /></label><button className="button button-accent" type="submit">Request booking <ArrowRight size={16} /></button><p className="form-disclaimer">This is a booking request, not a confirmed appointment. We will confirm availability with you.</p></form></>}</div></div>}
    </div>
  );
}

function SectionHeading({ eyebrow, title, intro, action }: { eyebrow: string; title: ReactNode; intro?: string; action?: ReactNode }) { return <div className="section-heading"><div><p className="eyebrow"><span className="eyebrow-line" /> {eyebrow}</p><h2>{title}</h2></div>{intro && <div className="heading-side"><p>{intro}</p>{action}</div>}</div>; }
export default App;
