import type { MenuItem, Category } from './types';

export const categories: Category[] = [
  {
    slug: 'idli-vada',
    name: 'Idli & Vada',
    shortName: 'Idli & Vada',
    description: 'Soft steamed idlis and crispy golden vadas with sambhar and chutney.',
    tagline: 'Soft idlis, crispy vadas and comforting South Indian flavours.',
    image: 'https://images.pexels.com/photos/8312083/pexels-photo-8312083.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    slug: 'dosa',
    name: 'Dosa',
    shortName: 'Dosa',
    description: 'Crispy, golden dosas made fresh on the griddle with a variety of fillings.',
    tagline: 'Crispy golden dosas made fresh on the griddle.',
    image: 'https://images.pexels.com/photos/20422138/pexels-photo-20422138.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    slug: 'uttapam',
    name: 'Uttapam',
    shortName: 'Uttapam',
    description: 'Thick, savoury rice pancakes topped with fresh vegetables and cheese.',
    tagline: 'Thick, savoury pancakes loaded with toppings.',
    image: 'https://images.pexels.com/photos/20422130/pexels-photo-20422130.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    slug: 'chaat',
    name: 'Chaat & Snacks',
    shortName: 'Chaat',
    description: 'Crunchy, tangy Indian street snacks and savoury bites.',
    tagline: 'Crunchy, tangy Indian street snacks and savoury bites.',
    image: 'https://images.pexels.com/photos/14477873/pexels-photo-14477873.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    slug: 'beverages',
    name: 'Beverages',
    shortName: 'Beverages',
    description: 'Filter coffee, masala chai and refreshing drinks.',
    tagline: 'Filter coffee, masala chai and refreshing drinks.',
    image: 'https://images.pexels.com/photos/38201891/pexels-photo-38201891.png?auto=compress&cs=tinysrgb&h=650&w=940',
  },
];

export const menu: MenuItem[] = [
  // Idli & Vada
  {
    id: 'idli-plate',
    slug: 'idli-plate',
    name: 'Idli Plate',
    category: 'idli-vada',
    description: 'Soft steamed rice idlis served with sambhar and coconut chutney.',
    price: 50,
    image: 'https://images.pexels.com/photos/31199041/pexels-photo-31199041.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '2 pieces',
    includes: ['2 idli', 'Sambhar', 'Coconut chutney'],
  },
  {
    id: 'idli-sambhar',
    slug: 'idli-sambhar',
    name: 'Idli Sambhar',
    category: 'idli-vada',
    description: 'Soft steamed idlis paired with comforting sambhar and fresh chutney.',
    price: 60,
    image: 'https://images.pexels.com/photos/35514447/pexels-photo-35514447.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    bestseller: true,
    available: 'available',
    serves: '3 pieces',
    includes: ['3 idli', 'Extra sambhar', 'Coconut chutney', 'Tomato chutney'],
  },
  {
    id: 'vada-plate',
    slug: 'vada-plate',
    name: 'Vada Plate',
    category: 'idli-vada',
    description: 'Crispy outside, soft inside — medu vada served with classic accompaniments.',
    price: 70,
    image: 'https://images.pexels.com/photos/37421009/pexels-photo-37421009.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    bestseller: true,
    available: 'available',
    serves: '2 pieces',
    includes: ['2 medu vada', 'Sambhar', 'Coconut chutney'],
  },
  {
    id: 'idli-vada-combo',
    slug: 'idli-vada-combo',
    name: 'Idli Vada Combo',
    category: 'idli-vada',
    description: 'The best of both — soft idli and crispy vada on one plate.',
    price: 90,
    image: 'https://images.pexels.com/photos/37867687/pexels-photo-37867687.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    popular: true,
    available: 'available',
    serves: '2 idli + 2 vada',
    includes: ['2 idli', '2 medu vada', 'Sambhar', 'Two chutneys'],
  },
  {
    id: 'extra-sambhar',
    slug: 'extra-sambhar',
    name: 'Extra Sambhar',
    category: 'idli-vada',
    description: 'A bowl of comforting lentil sambhar for dipping.',
    price: 25,
    image: 'https://images.pexels.com/photos/36854501/pexels-photo-36854501.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 bowl',
  },
  {
    id: 'extra-chutney',
    slug: 'extra-chutney',
    name: 'Extra Chutney',
    category: 'idli-vada',
    description: 'Fresh coconut chutney, the perfect side.',
    price: 20,
    image: 'https://images.pexels.com/photos/28915086/pexels-photo-28915086.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 portion',
  },

  // Dosa
  {
    id: 'plain-dosa',
    slug: 'plain-dosa',
    name: 'Plain Dosa',
    category: 'dosa',
    description: 'Crispy golden rice and lentil crepe with sambhar and chutney.',
    price: 60,
    image: 'https://images.pexels.com/photos/20422121/pexels-photo-20422121.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 piece',
    includes: ['1 dosa', 'Sambhar', 'Coconut chutney', 'Tomato chutney'],
  },
  {
    id: 'masala-dosa',
    slug: 'masala-dosa',
    name: 'Masala Dosa',
    category: 'dosa',
    description: 'Crispy golden dosa filled with flavourful potato masala, served with sambhar and chutney.',
    price: 90,
    image: 'https://images.pexels.com/photos/12392915/pexels-photo-12392915.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    bestseller: true,
    available: 'available',
    serves: '1 piece',
    includes: ['1 dosa', 'Potato masala', 'Sambhar', 'Two chutneys'],
  },
  {
    id: 'butter-dosa',
    slug: 'butter-dosa',
    name: 'Butter Dosa',
    category: 'dosa',
    description: 'Crispy dosa roasted with rich butter for an extra indulgent taste.',
    price: 100,
    image: 'https://images.pexels.com/photos/20422133/pexels-photo-20422133.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    popular: true,
    available: 'available',
    serves: '1 piece',
    includes: ['1 dosa', 'Sambhar', 'Two chutneys'],
  },
  {
    id: 'cheese-dosa',
    slug: 'cheese-dosa',
    name: 'Cheese Dosa',
    category: 'dosa',
    description: 'Crispy dosa loaded with melted cheese — a cheesy favourite.',
    price: 120,
    image: 'https://images.pexels.com/photos/39104603/pexels-photo-39104603.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    bestseller: true,
    available: 'available',
    serves: '1 piece',
    includes: ['1 dosa', 'Cheese filling', 'Sambhar', 'Chutney'],
  },
  {
    id: 'rava-dosa',
    slug: 'rava-dosa',
    name: 'Rava Dosa',
    category: 'dosa',
    description: 'Lacy, crispy semolina dosa with a delicate crunch.',
    price: 100,
    image: 'https://images.pexels.com/photos/28107046/pexels-photo-28107046.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 piece',
    includes: ['1 dosa', 'Sambhar', 'Chutney'],
  },
  {
    id: 'onion-rava-dosa',
    slug: 'onion-rava-dosa',
    name: 'Onion Rava Dosa',
    category: 'dosa',
    description: 'Crispy rava dosa topped with finely chopped onions and herbs.',
    price: 110,
    image: 'https://images.pexels.com/photos/20422123/pexels-photo-20422123.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 piece',
    includes: ['1 dosa', 'Onion topping', 'Sambhar', 'Chutney'],
  },
  {
    id: 'cheese-rava-dosa',
    slug: 'cheese-rava-dosa',
    name: 'Cheese Rava Dosa',
    category: 'dosa',
    description: 'Lacy rava dosa with a generous layer of melted cheese.',
    price: 130,
    image: 'https://images.pexels.com/photos/32229637/pexels-photo-32229637.png?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    popular: true,
    available: 'available',
    serves: '1 piece',
    includes: ['1 dosa', 'Cheese', 'Sambhar', 'Chutney'],
  },
  {
    id: 'mysore-masala-dosa',
    slug: 'mysore-masala-dosa',
    name: 'Mysore Masala Dosa',
    category: 'dosa',
    description: 'Spicy red chutney smeared inside a crispy dosa with potato masala.',
    price: 110,
    image: 'https://images.pexels.com/photos/38201890/pexels-photo-38201890.png?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    spicy: true,
    spiceLevel: 'spicy',
    available: 'available',
    serves: '1 piece',
    includes: ['1 dosa', 'Mysore chutney', 'Potato masala', 'Sambhar'],
  },
  {
    id: 'paneer-dosa',
    slug: 'paneer-dosa',
    name: 'Paneer Dosa',
    category: 'dosa',
    description: 'Crispy dosa stuffed with spiced paneer filling.',
    price: 130,
    image: 'https://images.pexels.com/photos/20422131/pexels-photo-20422131.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    isNew: true,
    available: 'available',
    serves: '1 piece',
    includes: ['1 dosa', 'Paneer filling', 'Sambhar', 'Chutney'],
  },

  // Uttapam
  {
    id: 'plain-uttapam',
    slug: 'plain-uttapam',
    name: 'Plain Uttapam',
    category: 'uttapam',
    description: 'Thick, soft rice pancake served with sambhar and chutney.',
    price: 70,
    image: 'https://images.pexels.com/photos/17869140/pexels-photo-17869140.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 piece',
    includes: ['1 uttapam', 'Sambhar', 'Chutney'],
  },
  {
    id: 'onion-uttapam',
    slug: 'onion-uttapam',
    name: 'Onion Uttapam',
    category: 'uttapam',
    description: 'Savoury uttapam topped with finely chopped onions and coriander.',
    price: 80,
    image: 'https://images.pexels.com/photos/38201893/pexels-photo-38201893.png?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    bestseller: true,
    available: 'available',
    serves: '1 piece',
    includes: ['1 uttapam', 'Onion topping', 'Sambhar', 'Chutney'],
  },
  {
    id: 'tomato-uttapam',
    slug: 'tomato-uttapam',
    name: 'Tomato Uttapam',
    category: 'uttapam',
    description: 'Fresh tomato and herb topped uttapam, light and tangy.',
    price: 80,
    image: 'https://images.pexels.com/photos/28915087/pexels-photo-28915087.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 piece',
    includes: ['1 uttapam', 'Tomato topping', 'Sambhar', 'Chutney'],
  },
  {
    id: 'onion-tomato-uttapam',
    slug: 'onion-tomato-uttapam',
    name: 'Onion Tomato Uttapam',
    category: 'uttapam',
    description: 'Loaded with onions and tomatoes for a hearty, colourful uttapam.',
    price: 90,
    image: 'https://images.pexels.com/photos/36854500/pexels-photo-36854500.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    popular: true,
    available: 'available',
    serves: '1 piece',
    includes: ['1 uttapam', 'Onion & tomato', 'Sambhar', 'Chutney'],
  },
  {
    id: 'cheese-uttapam',
    slug: 'cheese-uttapam',
    name: 'Cheese Uttapam',
    category: 'uttapam',
    description: 'Soft uttapam topped with a generous layer of melted cheese.',
    price: 110,
    image: 'https://images.pexels.com/photos/20422130/pexels-photo-20422130.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 piece',
    includes: ['1 uttapam', 'Cheese', 'Sambhar', 'Chutney'],
  },
  {
    id: 'special-uttapam',
    slug: 'special-uttapam',
    name: 'Special Uttapam',
    category: 'uttapam',
    description: 'Our signature uttapam with mixed vegetables, cheese and herbs.',
    price: 130,
    image: 'https://images.pexels.com/photos/20422126/pexels-photo-20422126.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    isNew: true,
    available: 'available',
    serves: '1 piece',
    includes: ['1 uttapam', 'Mixed veg', 'Cheese', 'Sambhar', 'Chutney'],
  },

  // Chaat & Snacks
  {
    id: 'samosa',
    slug: 'samosa',
    name: 'Samosa',
    category: 'chaat',
    description: 'Crispy pastry filled with spiced potatoes and peas.',
    price: 30,
    image: 'https://images.pexels.com/photos/14477873/pexels-photo-14477873.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    bestseller: true,
    available: 'available',
    serves: '2 pieces',
    includes: ['2 samosa', 'Mint chutney', 'Tamarind chutney'],
  },
  {
    id: 'samosa-chaat',
    slug: 'samosa-chaat',
    name: 'Samosa Chaat',
    category: 'chaat',
    description: 'Crushed samosa topped with chickpeas, yoghurt and chutneys.',
    price: 60,
    image: 'https://images.pexels.com/photos/37153389/pexels-photo-37153389.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    spicy: true,
    spiceLevel: 'medium',
    available: 'available',
    serves: '1 plate',
  },
  {
    id: 'aloo-chaat',
    slug: 'aloo-chaat',
    name: 'Aloo Chaat',
    category: 'chaat',
    description: 'Spiced potato cubes tossed with tangy chutneys and sev.',
    price: 50,
    image: 'https://images.pexels.com/photos/34968010/pexels-photo-34968010.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 plate',
  },
  {
    id: 'papdi-chaat',
    slug: 'papdi-chaat',
    name: 'Papdi Chaat',
    category: 'chaat',
    description: 'Crisp papdi with chickpeas, yoghurt and sweet-tangy chutneys.',
    price: 55,
    image: 'https://images.pexels.com/photos/35113190/pexels-photo-35113190.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 plate',
  },
  {
    id: 'dahi-chaat',
    slug: 'dahi-chaat',
    name: 'Dahi Chaat',
    category: 'chaat',
    description: 'Crispy snacks topped with chilled yoghurt and chutneys.',
    price: 50,
    image: 'https://images.pexels.com/photos/34270741/pexels-photo-34270741.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 plate',
  },
  {
    id: 'bhel',
    slug: 'bhel',
    name: 'Bhel',
    category: 'chaat',
    description: 'Puffed rice tossed with tangy tamarind, chutneys and sev.',
    price: 40,
    image: 'https://images.pexels.com/photos/35213277/pexels-photo-35213277.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 plate',
  },
  {
    id: 'sev-puri',
    slug: 'sev-puri',
    name: 'Sev Puri',
    category: 'chaat',
    description: 'Crisp puris topped with potatoes, chutneys and crunchy sev.',
    price: 50,
    image: 'https://images.pexels.com/photos/36195516/pexels-photo-36195516.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    spicy: true,
    spiceLevel: 'spicy',
    available: 'available',
    serves: '1 plate',
  },

  // Beverages
  {
    id: 'filter-coffee',
    slug: 'filter-coffee',
    name: 'Filter Coffee',
    category: 'beverages',
    description: 'Authentic South Indian filter coffee, frothy and aromatic.',
    price: 40,
    image: 'https://images.pexels.com/photos/38201891/pexels-photo-38201891.png?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    bestseller: true,
    available: 'available',
    serves: '1 glass',
  },
  {
    id: 'masala-tea',
    slug: 'masala-tea',
    name: 'Masala Tea',
    category: 'beverages',
    description: 'Spiced Indian masala chai brewed with milk and aromatic spices.',
    price: 30,
    image: 'https://images.pexels.com/photos/37186989/pexels-photo-37186989.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    bestseller: true,
    available: 'available',
    serves: '1 glass',
  },
  {
    id: 'tea',
    slug: 'tea',
    name: 'Tea',
    category: 'beverages',
    description: 'Regular Indian chai, simple and comforting.',
    price: 20,
    image: 'https://images.pexels.com/photos/2697931/pexels-photo-2697931.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 glass',
  },
  {
    id: 'coffee',
    slug: 'coffee',
    name: 'Coffee',
    category: 'beverages',
    description: 'Regular instant coffee, hot and refreshing.',
    price: 25,
    image: 'https://images.pexels.com/photos/33932441/pexels-photo-33932441.png?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 glass',
  },
  {
    id: 'buttermilk',
    slug: 'buttermilk',
    name: 'Buttermilk',
    category: 'beverages',
    description: 'Spiced buttermilk, cool and refreshing.',
    price: 30,
    image: 'https://images.pexels.com/photos/8489749/pexels-photo-8489749.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 glass',
  },
  {
    id: 'soft-drinks',
    slug: 'soft-drinks',
    name: 'Soft Drinks',
    category: 'beverages',
    description: 'Chilled bottled soft drinks.',
    price: 40,
    image: 'https://images.pexels.com/photos/15522898/pexels-photo-15522898.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 bottle',
  },
  {
    id: 'water',
    slug: 'water',
    name: 'Water Bottle',
    category: 'beverages',
    description: 'Packaged mineral water.',
    price: 20,
    image: 'https://images.pexels.com/photos/16128085/pexels-photo-16128085.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    vegetarian: true,
    available: 'available',
    serves: '1 bottle',
  },
];

export function getItemBySlug(slug: string): MenuItem | undefined {
  return menu.find((m) => m.slug === slug);
}

export function getItemsByCategory(category: string): MenuItem[] {
  if (!category || category === 'all') return menu;
  return menu.filter((m) => m.category === category);
}

export function getRelatedItems(item: MenuItem, count = 3): MenuItem[] {
  return menu
    .filter((m) => m.category === item.category && m.id !== item.id)
    .slice(0, count);
}

export function getPopularItems(count = 8): MenuItem[] {
  return menu.filter((m) => m.bestseller || m.popular).slice(0, count);
}

export function formatPrice(price: number): string {
  return `₹${price}`;
}
